force-app/main/default/objects/Account/fields/Substance__c.field-meta.xml
<CustomField>
    <fullName>Substance__c</fullName>
    <label>Substance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cocaine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DailyModule__c/DailyModule__c.object-meta.xml
<CustomObject>
    <label>Daily Module</label>
    <nameField>
        <label>Daily Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DailyModule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Daily Modules</relationshipLabel>
    <relationshipName>Daily_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DailyModule__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Daily Modules</relationshipLabel>
    <relationshipName>Daily_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cocaine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/DailyModuleScheduledTest.cls
@isTest
public class DailyModuleScheduledTest {
	public static String CRON_EXP = '0 0 0 15 3 ? 2022';

	@testSetup
	static void setupData() {
		List<Account> patients = new List<Account>();
		patients.add(
			TestDataFactory.generateSinglePersonAccount(
				DailyModuleScheduled.SUBSTANCE_ALCOHOL
			)
		);
		patients.add(
			TestDataFactory.generateSinglePersonAccount(
				DailyModuleScheduled.SUBSTANCE_CANNABIS
			)
		);
		patients.add(
			TestDataFactory.generateSinglePersonAccount(
				DailyModuleScheduled.SUBSTANCE_COCAINE
			)
		);
		insert patients;

		List<Module__c> modules = TestDataFactory.generateModules();
		insert modules;
	}

	@isTest
	static void shouldAssignDailyModuleWhereActive() {
		Test.startTest();

		String jobId = System.schedule(
			'ScheduledApexTest',
			CRON_EXP,
			new DailyModuleScheduled()
		);

		Test.stopTest();

		List<DailyModule__c> dailyModules = [
			SELECT Id, Module__r.Type__c, Account__r.Substance__c
			FROM DailyModule__c
		];

		System.assertNotEquals(0, dailyModules.size());

		for (DailyModule__c dm : dailyModules) {
			System.assert(dm.Module__r.Type__c == dm.Account__r.Substance__c || dm.Module__r.Type__c == DailyModuleScheduled.SUBSTANCE_ANY);
		}
	}
}