force-app/main/default/objects/Account/fields/Substance__c.field-meta.xml
<CustomField>
    <fullName>Substance__c</fullName>
    <label>Substance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cocaine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any</fullName>
            </value>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>Cannabis</fullName>
            </value>
            <value>
                <fullName>Cocaine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The URL for the Module (Community page or external resource)</description>
    <label>URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/tests/TestDataFactory.cls
@isTest
public class TestDataFactory {
	// Genarates a single Person Account record
	public static Account generateSinglePersonAccount(String substance) {
		Id recTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
			.get('PersonAccount')
			.getRecordTypeId();
		Account acc = new Account(
			FirstName = generateRandomString(5),
			LastName = generateRandomString(8),
			Substance__c = substance,
			RecordTypeId = rectypeId
		);

		return acc;
	}

	// Generates some sample Modules for test data
	public static List<Module__c> generateModules() {
		List<Module__c> mods = new List<Module__c>();
		List<String> moduleTypes = new List<String>{
			DailyModuleScheduled.SUBSTANCE_ANY,
			DailyModuleScheduled.SUBSTANCE_ALCOHOL,
			DailyModuleScheduled.SUBSTANCE_CANNABIS,
			DailyModuleScheduled.SUBSTANCE_COCAINE
		};

		for (String s : moduleTypes) {
			for (Integer i = 0; i < 10; i++) {
				mods.add(new Module__c(URL__c = generateRandomString(30), Type__c = s));
			}
		}

		return mods;
	}

	public static String generateRandomString(Integer len) {
		final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
		String randStr = '';
		while (randStr.length() < len) {
			Integer idx = Math.mod(
				Math.abs(Crypto.getRandomInteger()),
				chars.length()
			);
			randStr += chars.substring(idx, idx + 1);
		}
		return randStr;
	}
}